" ================ GUI Config =======================

set guioptions-=T               " Remove toolbar bar
set guioptions-=m               " Remove menu bar
set guioptions-=r               " Remove right-hand scroll bar
set guioptions-=L               " Remove left-hand scroll bar

set guifont=Droid\ Sans\ Mono\ 10

set background=dark
colorscheme solarized

let g:solarized_termcolors=256

" ================ Plugins ==========================

let g:airline_theme='solarized'
